import { describe, it, expect } from 'vitest';
import { centralPortalPlatformService } from '../services/centralPortalPlatformService';
import { UserAuthorizationContext } from '../types';

describe('SSIU ERP – Phase 13.39: Portal Platform & Self-Service Experience Engine', () => {

  const studentUser: UserAuthorizationContext = {
    userId: 'stu-2026-001',
    userName: 'Aarav Patel',
    email: 'aarav@swarrnim.edu.in',
    activeRole: 'STUDENT',
    assignedRoles: ['STUDENT'],
    permissions: ['SERVICE_VIEW', 'SERVICE_REQUEST', 'SERVICE_TRACK']
  };

  const facultyUser: UserAuthorizationContext = {
    userId: 'fac-2026-001',
    userName: 'Dr. Sharma',
    email: 'sharma@swarrnim.edu.in',
    activeRole: 'FACULTY',
    assignedRoles: ['FACULTY'],
    permissions: ['SERVICE_VIEW', 'SERVICE_REQUEST', 'SERVICE_TRACK']
  };

  const staffUser: UserAuthorizationContext = {
    userId: 'emp-staff-001',
    userName: 'Admissions Officer',
    email: 'admissions@swarrnim.edu.in',
    activeRole: 'REGISTRAR',
    assignedRoles: ['REGISTRAR'],
    permissions: ['SERVICE_APPROVE', 'SERVICE_COMPLETE', 'DOCUMENT_GOVERNANCE_VIEW']
  };

  it('TEST 1: Portal Navigation: Filters navigation items strictly by active role and permissions', () => {
    // 1. Student Navigation
    const studentNav = centralPortalPlatformService.getPortalNavigation('STUDENT_PORTAL', studentUser);
    const studentLabels = studentNav.map(n => n.label);
    expect(studentLabels).toContain('My Attendance');
    expect(studentLabels).toContain('Class Timetable');
    expect(studentLabels).not.toContain('Faculty Workload');

    // 2. Faculty Navigation
    const facultyNav = centralPortalPlatformService.getPortalNavigation('FACULTY_PORTAL', facultyUser);
    const facultyLabels = facultyNav.map(n => n.label);
    expect(facultyLabels).toContain('Faculty Workload');
    expect(facultyLabels).not.toContain('My Attendance');
  });

  it('TEST 2: Self-Service Catalog & Eligibility Gate: Enforces role eligibility for service requests', () => {
    // 1. Eligible student submits Bonafide request
    const request = centralPortalPlatformService.submitServiceRequest({
      serviceCode: 'SRV-BONAFIDE-CERT',
      attachedDocumentIds: ['dms-doc-fee-receipt-001'],
      context: studentUser
    });

    expect(request.id).toBeDefined();
    expect(request.request_number).toMatch(/^SR-2026-\d{6}$/);
    expect(request.status).toBe('SUBMITTED');
    expect(request.requester_role).toBe('STUDENT');

    // 2. Ineligible student attempts to submit Faculty Leave request
    expect(() => {
      centralPortalPlatformService.submitServiceRequest({
        serviceCode: 'SRV-FACULTY-LEAVE',
        context: studentUser
      });
    }).toThrow(/Service Ineligibility: User with role STUDENT is not eligible/);
  });

  it('TEST 3: Request Comments & Internal Privacy Gate: Protects confidential internal staff notes from requester', () => {
    const request = centralPortalPlatformService.submitServiceRequest({
      serviceCode: 'SRV-BONAFIDE-CERT',
      context: studentUser
    });

    // 1. Staff adds internal confidential note
    centralPortalPlatformService.addRequestComment({
      requestId: request.id,
      commentText: 'Verified fee clearance with Finance desk; applicant has no outstanding dues.',
      isInternalOnly: true,
      context: staffUser
    });

    // 2. Staff adds public requester update
    centralPortalPlatformService.addRequestComment({
      requestId: request.id,
      commentText: 'Your certificate is being generated by Registrar office.',
      isInternalOnly: false,
      context: staffUser
    });

    // Student must ONLY see the public comment
    const studentComments = centralPortalPlatformService.getRequestComments(request.id, studentUser);
    expect(studentComments.length).toBe(1);
    expect(studentComments[0].is_internal_only).toBe(false);

    // Staff sees both comments
    const staffComments = centralPortalPlatformService.getRequestComments(request.id, staffUser);
    expect(staffComments.length).toBe(2);
  });

  it('TEST 4: Organization Context Switching: Seamlessly updates session context', () => {
    const result = centralPortalPlatformService.switchPortalOrganizationContext('inst-sit-campus-2', studentUser);
    expect(result.newOrgId).toBe('inst-sit-campus-2');
    expect(result.status).toContain('Successfully switched');
  });

  it('TEST 5: Portal Platform Dashboard Telemetry: Validates active users, SLA compliance, and posture', () => {
    const metrics = centralPortalPlatformService.getPortalDashboardMetrics(studentUser);

    expect(metrics.activeUsersCount).toBeGreaterThan(1000);
    expect(metrics.totalServiceRequestsCount).toBeGreaterThanOrEqual(1);
    expect(metrics.slaCompliancePercent).toBeGreaterThanOrEqual(95);
    expect(metrics.portalHealthPosture).toBe('HEALTHY');
  });
});
