import { Injectable, Logger } from '@nestjs/common';
import * as XLSX from 'xlsx';

@Injectable()
export class AccreditationExportService {
  private readonly logger = new Logger(AccreditationExportService.name);

  /**
   * Serializes the sealed snapshot as a structured canonical JSON export.
   */
  exportJson(report: any) {
    const snapshot = report.snapshotData;
    return {
      reportId: report.reportId,
      framework: report.framework,
      version: report.version,
      academicYearRange: report.academicYearRange,
      status: report.status,
      hash: report.hash,
      generatedBy: report.generatedBy,
      generatedAt: report.generatedAt,
      snapshot,
    };
  }

  /**
   * Generates a multi-sheet Microsoft Excel (.xlsx) workbook buffer from the sealed snapshot.
   */
  exportExcelBuffer(report: any): Buffer {
    const snapshot = report.snapshotData || {};
    const criteria = snapshot.criteria || [];
    const framework = report.framework;

    const wb = XLSX.utils.book_new();

    // 1. Sheet 1: Report Summary
    const summaryData = [
      ['ACCREDITATION REPORT SUMMARY', ''],
      ['Report ID', report.reportId],
      ['Framework', framework],
      ['Version', report.version || 'v1.0'],
      ['Academic Cycle', report.academicYearRange],
      ['Status', report.status],
      ['Integrity Hash (SHA-256)', report.hash || 'N/A'],
      ['Generated By', report.generatedBy],
      ['Generated At', new Date(report.generatedAt).toLocaleString('en-IN')],
      ['Institution', snapshot.institution?.name || 'Swarrnim Startup & Innovation University'],
      ['AISHE Code', snapshot.institution?.aisheCode || 'U-0894'],
      ['Campus', snapshot.institution?.campus || 'Gandhinagar, Gujarat'],
      ['Total Criteria', criteria.length],
    ];
    const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(wb, wsSummary, 'Report Summary');

    // 2. Sheet 2: Criteria Summary
    const criteriaData = [
      ['Criterion Number', 'Code', 'Title', 'Weightage', 'Metrics Count'],
      ...criteria.map((c: any) => [
        c.criterionNumber,
        c.code,
        c.title,
        c.weightage,
        c.metrics?.length || 0,
      ]),
    ];
    const wsCriteria = XLSX.utils.aoa_to_sheet(criteriaData);
    XLSX.utils.book_append_sheet(wb, wsCriteria, 'Criteria');

    // 3. Sheet 3: 5-Year Metric Data
    const metricHeaders = [
      'Criterion',
      'Metric Code',
      'Metric Name',
      'Unit',
      'Source Module',
      'Academic Year',
      'Value',
      'Status',
      'Source Count',
      'Reference Detail',
    ];
    const metricRows: any[] = [];
    criteria.forEach((c: any) => {
      (c.metrics || []).forEach((m: any) => {
        (m.fiveYearValues || []).forEach((v: any) => {
          metricRows.push([
            c.code,
            m.code,
            m.name,
            m.unit || 'Score',
            m.sourceModule || 'ERP',
            v.academicYear,
            v.value,
            v.status,
            v.sourceRecordCount,
            v.sourceRecordReference || '',
          ]);
        });
      });
    });
    const wsMetrics = XLSX.utils.aoa_to_sheet([metricHeaders, ...metricRows]);
    XLSX.utils.book_append_sheet(wb, wsMetrics, '5-Year Metric Data');

    // 4. Sheet 4: Evidence Registry
    const evidenceHeaders = [
      'Metric Code',
      'Evidence ID',
      'Title',
      'Type',
      'Source',
      'Academic Year',
      'Status',
      'Verified By',
      'Rejection Reason',
    ];
    const evidenceRows: any[] = [];
    criteria.forEach((c: any) => {
      (c.metrics || []).forEach((m: any) => {
        (m.evidences || []).forEach((e: any) => {
          evidenceRows.push([
            m.code,
            e.id,
            e.title,
            e.evidenceType,
            e.sourceModule,
            e.academicYear,
            e.status,
            e.verifiedBy || '',
            e.rejectionReason || '',
          ]);
        });
      });
    });
    const wsEvidence = XLSX.utils.aoa_to_sheet([evidenceHeaders, ...evidenceRows]);
    XLSX.utils.book_append_sheet(wb, wsEvidence, 'Evidence Registry');

    // 5. Sheet 5: Data Lineage & Traceability
    const lineageHeaders = ['Metric Code', 'Source Module', 'Source Entity', 'Source Record ID', 'Academic Year'];
    const lineageRows = (snapshot.dataLineageSample || []).map((l: any) => [
      l.metricCode,
      l.sourceModule,
      l.sourceEntity,
      l.sourceRecordId,
      l.academicYear,
    ]);
    const wsLineage = XLSX.utils.aoa_to_sheet([lineageHeaders, ...lineageRows]);
    XLSX.utils.book_append_sheet(wb, wsLineage, 'Data Lineage');

    // 6. Sheet 6: Integrity & Seal Verification
    const integrityData = [
      ['CRYPTOGRAPHIC INTEGRITY VERIFICATION LEDGER', ''],
      ['Report ID', report.reportId],
      ['Framework', framework],
      ['Digital Seal Hash', report.hash || 'N/A'],
      ['Algorithm', 'SHA-256 (Deterministic Canonical Representation)'],
      ['Seal Status', report.status === 'SEALED' ? 'LOCKED / IMMUTABLE' : 'OPEN / GENERATED'],
      ['Verification Note', 'Any bit-level alteration in metrics or evidence invalidates this hash.'],
    ];
    const wsIntegrity = XLSX.utils.aoa_to_sheet(integrityData);
    XLSX.utils.book_append_sheet(wb, wsIntegrity, 'Integrity Seal');

    return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
  }

  /**
   * Generates a print-ready self-contained HTML document with verified styling.
   */
  exportHtml(report: any): string {
    const snapshot = report.snapshotData || {};
    const criteria = snapshot.criteria || [];
    const framework = report.framework;
    const academicYears = ['2021-22', '2022-23', '2023-24', '2024-25', '2025-26'];

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${framework} Self-Study Report — ${report.reportId}</title>
  <style>
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1e293b; margin: 40px; line-height: 1.5; font-size: 13px; }
    .header { text-align: center; border-bottom: 2px solid #0f172a; padding-bottom: 20px; margin-bottom: 30px; }
    .header h1 { margin: 0 0 6px 0; font-size: 24px; color: #0f172a; }
    .header h2 { margin: 0 0 6px 0; font-size: 16px; color: #334155; font-weight: normal; }
    .meta-box { display: flex; justify-content: space-between; background: #f8fafc; border: 1px solid #e2e8f0; padding: 15px 20px; border-radius: 6px; margin-bottom: 30px; }
    .meta-item { font-size: 12px; }
    .meta-item strong { display: block; color: #64748b; font-size: 11px; text-transform: uppercase; }
    .criterion-section { margin-bottom: 35px; page-break-inside: avoid; }
    .criterion-title { background: #0f172a; color: #ffffff; padding: 8px 14px; font-size: 14px; font-weight: bold; border-radius: 4px; margin-bottom: 12px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 15px; font-size: 12px; }
    th { background: #f1f5f9; color: #334155; border: 1px solid #cbd5e1; padding: 8px 10px; text-align: left; font-weight: 600; }
    td { border: 1px solid #e2e8f0; padding: 8px 10px; }
    .badge { display: inline-block; padding: 2px 6px; border-radius: 4px; font-size: 10px; font-weight: bold; text-transform: uppercase; }
    .badge-valid { background: #dcfce7; color: #166534; }
    .badge-warning { background: #fef3c7; color: #92400e; }
    .badge-sealed { background: #e0e7ff; color: #3730a3; }
    .seal-box { background: #f8fafc; border: 2px dashed #94a3b8; border-radius: 6px; padding: 15px 20px; margin-top: 40px; font-family: monospace; font-size: 11px; }
    @media print { body { margin: 15mm; } .criterion-section { page-break-inside: avoid; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>${snapshot.institution?.name || 'Swarrnim Startup & Innovation University'}</h1>
    <h2>${framework} Self-Study Report (SSR / SAR) — Assessment Cycle ${report.academicYearRange}</h2>
    <div style="font-size: 12px; color: #64748b;">AISHE: ${snapshot.institution?.aisheCode || 'U-0894'} | Campus: ${snapshot.institution?.campus || 'Gandhinagar, Gujarat'}</div>
  </div>

  <div class="meta-box">
    <div class="meta-item"><strong>Report ID</strong>${report.reportId}</div>
    <div class="meta-item"><strong>Framework</strong>${framework} (${report.version})</div>
    <div class="meta-item"><strong>Status</strong><span class="badge badge-sealed">${report.status}</span></div>
    <div class="meta-item"><strong>Generated On</strong>${new Date(report.generatedAt).toLocaleDateString('en-IN')}</div>
    <div class="meta-item"><strong>Generated By</strong>${report.generatedBy}</div>
  </div>

  ${criteria
    .map(
      (c: any) => `
    <div class="criterion-section">
      <div class="criterion-title">${c.code}: ${c.title} (Weightage: ${c.weightage})</div>
      <table>
        <thead>
          <tr>
            <th style="width: 10%;">Metric</th>
            <th style="width: 35%;">Name & Description</th>
            <th style="width: 10%;">Unit</th>
            ${academicYears.map((yr) => `<th style="width: 8%; text-align: center;">${yr}</th>`).join('')}
            <th style="width: 5%; text-align: center;">Docs</th>
          </tr>
        </thead>
        <tbody>
          ${(c.metrics || [])
            .map((m: any) => {
              const valMap = new Map((m.fiveYearValues || []).map((v: any) => [v.academicYear, v.value]));
              return `
            <tr>
              <td><strong>${m.code}</strong></td>
              <td>${m.name}</td>
              <td>${m.unit || '-'}</td>
              ${academicYears
                .map((yr) => {
                  const val = valMap.get(yr);
                  return `<td style="text-align: center;">${val !== undefined ? val : '-'}</td>`;
                })
                .join('')}
              <td style="text-align: center;"><span class="badge badge-valid">${m.evidences?.length || 0}</span></td>
            </tr>
            `;
            })
            .join('')}
        </tbody>
      </table>
    </div>
  `,
    )
    .join('')}

  <div class="seal-box">
    <div><strong>CRYPTOGRAPHIC INTEGRITY SEAL (SHA-256)</strong></div>
    <div style="margin: 6px 0; color: #0284c7; word-break: break-all;">${report.hash || 'N/A'}</div>
    <div style="color: #64748b;">Deterministic canonical digest computed from institutional source records. Verification status: <strong style="color: #166534;">VALID & IMMUTABLE</strong></div>
  </div>
</body>
</html>`;
  }
}
