import React, { useState, useMemo } from 'react';
import { 
  DashboardReportType, ReportFilterOptions, reportEngine, MultiRecordReportData 
} from '../../services/reportService';
import { ReportPreviewModal } from './ReportPreviewModal';
import { Badge } from '../common/Badge';
import { 
  FileText, Download, Printer, X, ShieldCheck, CheckCircle2, 
  BarChart3, RefreshCw, Eye, ArrowRight 
} from 'lucide-react';

interface DashboardReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  dashboardType: DashboardReportType;
  currentFilters?: ReportFilterOptions;
  user?: any;
  role?: string | null;
}

export const DashboardReportModal: React.FC<DashboardReportModalProps> = ({
  isOpen,
  onClose,
  dashboardType,
  currentFilters = {},
  user,
  role
}) => {
  const [showFullPreview, setShowFullPreview] = useState(false);

  const reportData = useMemo<MultiRecordReportData>(() => {
    return reportEngine.generateDashboardReport(dashboardType, currentFilters, role, user);
  }, [dashboardType, currentFilters, role, user]);

  if (!isOpen) return null;

  const generatedByStr = user?.name ? `${user.name} (${role || 'OFFICER'})` : 'Authorized ERP Officer';

  const handlePrint = () => {
    const filterStr = reportData.appliedFilters.map(f => `${f.label}: ${f.value}`).join(' | ');
    reportEngine.triggerPrint(reportData.reportTitle, reportData.moduleName, generatedByStr, filterStr, reportData.totalCount);
  };

  const handleExcel = () => {
    reportEngine.exportExcel(reportData);
  };

  return (
    <>
      <div
        style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          backgroundColor: 'rgba(15, 23, 42, 0.7)',
          backdropFilter: 'blur(6px)',
          zIndex: 9990,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '1.5rem'
        }}
      >
        <div
          style={{
            backgroundColor: '#FFFFFF',
            borderRadius: '16px',
            width: '100%',
            maxWidth: '900px',
            maxHeight: '85vh',
            display: 'flex',
            flexDirection: 'column',
            boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
            overflow: 'hidden'
          }}
        >
          {/* Header */}
          <div
            style={{
              padding: '1.25rem 1.5rem',
              backgroundColor: '#0F2C59',
              color: '#FFFFFF',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center'
            }}
          >
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <FileText size={20} color="#F37023" />
                <h3 style={{ fontSize: '1.125rem', fontWeight: 800, margin: 0 }}>
                  Dashboard Analytics &amp; Compliance Report
                </h3>
              </div>
              <p style={{ fontSize: '0.75rem', color: '#94A3B8', marginTop: '2px', margin: 0 }}>
                Auto-generated using current active dashboard filters • Real ERP data
              </p>
            </div>

            <button
              onClick={onClose}
              style={{
                backgroundColor: 'transparent',
                color: '#FFFFFF',
                border: 'none',
                cursor: 'pointer',
                padding: '4px',
                display: 'flex',
                alignItems: 'center'
              }}
            >
              <X size={20} />
            </button>
          </div>

          {/* Content Body */}
          <div style={{ padding: '1.5rem', overflowY: 'auto', flex: 1, display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
            {/* Title & Metadata */}
            <div style={{ borderBottom: '1px solid #E2E8F0', paddingBottom: '1rem' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '0.75rem' }}>
                <div>
                  <h4 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#0F2C59', margin: 0 }}>
                    {reportData.reportTitle}
                  </h4>
                  <div style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap', marginTop: '0.35rem', fontSize: '0.75rem', color: '#64748B' }}>
                    <span>Generated By: <strong>{reportData.generatedBy}</strong></span>
                    <span>Date: <strong>{reportData.generatedDate}</strong></span>
                    <span>Total Records: <strong>{reportData.totalCount}</strong></span>
                  </div>
                </div>

                <Badge variant="navy">{reportData.moduleName.toUpperCase()}</Badge>
              </div>

              {/* Active Applied Filters */}
              <div style={{ display: 'flex', gap: '0.4rem', flexWrap: 'wrap', marginTop: '0.75rem' }}>
                <span style={{ fontSize: '0.6875rem', fontWeight: 700, color: '#64748B' }}>Inherited Filters:</span>
                {reportData.appliedFilters.map((f, i) => (
                  <span
                    key={i}
                    style={{
                      backgroundColor: '#F1F5F9',
                      border: '1px solid #CBD5E1',
                      padding: '1px 6px',
                      borderRadius: '4px',
                      fontSize: '0.6875rem',
                      fontWeight: 600,
                      color: '#0F2C59'
                    }}
                  >
                    {f.label}: {f.value}
                  </span>
                ))}
              </div>
            </div>

            {/* Summary KPI Metrics */}
            <div>
              <h5 style={{ fontSize: '0.875rem', fontWeight: 800, color: '#0F2C59', marginBottom: '0.5rem' }}>
                Executive Analytics Summary
              </h5>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '0.75rem' }}>
                {reportData.summaryMetrics.map((m, i) => (
                  <div
                    key={i}
                    style={{
                      padding: '0.85rem',
                      backgroundColor: '#F8FAFC',
                      borderRadius: '10px',
                      border: '1px solid #E2E8F0',
                      borderLeft: `3px solid ${m.color || '#0F2C59'}`
                    }}
                  >
                    <div style={{ fontSize: '0.6875rem', fontWeight: 700, color: '#64748B' }}>{m.label}</div>
                    <div style={{ fontSize: '1.25rem', fontWeight: 800, color: '#0F2C59', marginTop: '2px' }}>
                      {m.value}
                    </div>
                    {m.sublabel && (
                      <div style={{ fontSize: '0.6875rem', color: '#94A3B8', marginTop: '2px' }}>{m.sublabel}</div>
                    )}
                  </div>
                ))}
              </div>
            </div>

            {/* Quick Data Records Preview */}
            <div>
              <h5 style={{ fontSize: '0.875rem', fontWeight: 800, color: '#0F2C59', marginBottom: '0.5rem' }}>
                Itemized Records Sample
              </h5>
              <div style={{ overflowX: 'auto', maxHeight: '220px', border: '1px solid #E2E8F0', borderRadius: '8px' }}>
                <table className="table" style={{ width: '100%', fontSize: '0.75rem' }}>
                  <thead style={{ backgroundColor: '#F8FAFC', position: 'sticky', top: 0 }}>
                    <tr>
                      {reportData.headers.map((h, i) => (
                        <th key={i} style={{ padding: '0.5rem 0.75rem', fontWeight: 700, color: '#0F2C59' }}>{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {reportData.rows.slice(0, 15).map((row, rIdx) => (
                      <tr key={rIdx} style={{ borderBottom: '1px solid #F1F5F9' }}>
                        {row.map((cell, cIdx) => (
                          <td key={cIdx} style={{ padding: '0.5rem 0.75rem' }}>{cell}</td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              {reportData.rows.length > 15 && (
                <div style={{ textAlign: 'center', fontSize: '0.6875rem', color: '#64748B', marginTop: '4px' }}>
                  Previewing 15 of {reportData.rows.length} records. Full dataset available upon export.
                </div>
              )}
            </div>
          </div>

          {/* Footer Action Bar */}
          <div
            style={{
              padding: '1rem 1.5rem',
              backgroundColor: '#F8FAFC',
              borderTop: '1px solid #E2E8F0',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              flexWrap: 'wrap',
              gap: '0.75rem'
            }}
          >
            <button
              onClick={() => setShowFullPreview(true)}
              className="btn btn-secondary"
              style={{ fontSize: '0.8125rem', display: 'flex', alignItems: 'center', gap: '0.4rem' }}
            >
              <Eye size={15} /> View Official Letterhead Dossier
            </button>

            <div style={{ display: 'flex', gap: '0.6rem' }}>
              <button
                onClick={handlePrint}
                className="btn btn-primary"
                style={{ fontSize: '0.8125rem', display: 'flex', alignItems: 'center', gap: '0.4rem' }}
              >
                <Printer size={15} /> Print / Save PDF
              </button>

              <button
                onClick={handleExcel}
                className="btn btn-secondary"
                style={{ fontSize: '0.8125rem', display: 'flex', alignItems: 'center', gap: '0.4rem' }}
              >
                <Download size={15} /> Export Multi-Sheet Excel
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Full Official Preview Modal */}
      {showFullPreview && (
        <ReportPreviewModal
          isOpen={showFullPreview}
          onClose={() => setShowFullPreview(false)}
          multiReport={reportData}
          user={user}
          role={role}
        />
      )}
    </>
  );
};
