import { UserRole } from '../types';
import * as XLSX from 'xlsx';

export interface ReportFilterOptions {
  instituteName?: string;
  departmentName?: string;
  programName?: string;
  academicYearName?: string;
  semesterName?: string;
  divisionName?: string;
  startDate?: string;
  endDate?: string;
  searchQuery?: string;
}

export interface UserExportMetadata {
  name?: string;
  role?: UserRole;
  designation?: string;
  email?: string;
}

/**
 * Format date for reports (e.g. 12 August 2026, 01:45 PM)
 */
const formatReportTimestamp = (): string => {
  const now = new Date();
  return now.toLocaleString('en-IN', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: true
  });
};

/**
 * Export dataset to Excel (.xlsx compatible CSV with UTF-8 BOM)
 */
export const exportToExcel = (
  reportTitle: string,
  headers: string[],
  rows: (string | number)[][],
  filters: ReportFilterOptions,
  userMeta?: UserExportMetadata
) => {
  const timestamp = formatReportTimestamp();
  
  // Format filter summary string
  const activeFilters = [
    filters.instituteName && filters.instituteName !== 'ALL' ? `Institute: ${filters.instituteName}` : null,
    filters.departmentName && filters.departmentName !== 'ALL' ? `Department: ${filters.departmentName}` : null,
    filters.programName && filters.programName !== 'ALL' ? `Program: ${filters.programName}` : null,
    filters.academicYearName && filters.academicYearName !== 'ALL' ? `Academic Year: ${filters.academicYearName}` : null,
    filters.semesterName && filters.semesterName !== 'ALL' ? `Semester: ${filters.semesterName}` : null,
    filters.divisionName && filters.divisionName !== 'ALL' ? `Division: ${filters.divisionName}` : null,
    filters.startDate ? `From: ${filters.startDate}` : null,
    filters.endDate ? `To: ${filters.endDate}` : null,
    filters.searchQuery ? `Search: "${filters.searchQuery}"` : null
  ].filter(Boolean).join(' | ') || 'All Records (Unfiltered)';

  // Build CSV content with metadata headers
  const csvLines: string[] = [
    `"SWARRNIM STARTUP & INNOVATION UNIVERSITY"`,
    `"OFFICIAL NAAC / UGC COMPLIANT ERP DATA REPORT"`,
    `"Report Title: ${reportTitle}"`,
    `"Generated On: ${timestamp}"`,
    `"Generated By: ${userMeta?.name || 'Authorized ERP User'} (${userMeta?.role || 'ERP User'})"`,
    `"Applied Filters: ${activeFilters}"`,
    `"Total Records: ${rows.length}"`,
    `""`, // Blank line separator
    headers.map(h => `"${h.replace(/"/g, '""')}"`).join(','),
    ...rows.map(row => 
      row.map(cell => {
        const strVal = cell === null || cell === undefined ? '' : String(cell);
        return `"${strVal.replace(/"/g, '""')}"`;
      }).join(',')
    )
  ];

  const csvString = '\uFEFF' + csvLines.join('\n');
  const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  const sanitizedTitle = reportTitle.toLowerCase().replace(/[^a-z0-9]/g, '_');
  link.setAttribute('href', url);
  link.setAttribute('download', `ssiu_report_${sanitizedTitle}_${new Date().toISOString().split('T')[0]}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Export dataset to Word Document (.doc with University Letterhead Styling)
 */
export const exportToWord = (
  reportTitle: string,
  headers: string[],
  rows: (string | number)[][],
  filters: ReportFilterOptions,
  userMeta?: UserExportMetadata
) => {
  const timestamp = formatReportTimestamp();
  
  const activeFilters = [
    filters.instituteName && filters.instituteName !== 'ALL' ? `Institute: ${filters.instituteName}` : null,
    filters.departmentName && filters.departmentName !== 'ALL' ? `Department: ${filters.departmentName}` : null,
    filters.programName && filters.programName !== 'ALL' ? `Program: ${filters.programName}` : null,
    filters.academicYearName && filters.academicYearName !== 'ALL' ? `Academic Year: ${filters.academicYearName}` : null,
    filters.semesterName && filters.semesterName !== 'ALL' ? `Semester: ${filters.semesterName}` : null,
    filters.divisionName && filters.divisionName !== 'ALL' ? `Division: ${filters.divisionName}` : null,
    filters.startDate ? `From: ${filters.startDate}` : null,
    filters.endDate ? `To: ${filters.endDate}` : null,
    filters.searchQuery ? `Search: "${filters.searchQuery}"` : null
  ].filter(Boolean).join(' | ') || 'All Records (Unfiltered)';

  const tableHeaderHtml = headers.map(h => 
    `<th style="background-color: #0F2C59; color: #FFFFFF; font-weight: bold; padding: 10px 8px; border: 1px solid #1E3E62; text-align: left; font-size: 11px; text-transform: uppercase;">${h}</th>`
  ).join('');

  const tableRowsHtml = rows.map((row, idx) => {
    const bg = idx % 2 === 0 ? '#FFFFFF' : '#F8FAFC';
    const cellsHtml = row.map(cell => 
      `<td style="padding: 8px; border: 1px solid #CBD5E1; font-size: 11px; color: #1E293B;">${cell === null || cell === undefined ? '' : String(cell)}</td>`
    ).join('');
    return `<tr style="background-color: ${bg};">${cellsHtml}</tr>`;
  }).join('');

  const htmlDocument = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
    <head>
      <meta charset="utf-8">
      <title>${reportTitle} - Swarrnim University</title>
      <style>
        @page {
          size: A4 portrait;
          margin: 20mm 15mm 20mm 15mm;
          @bottom-right {
            content: "Page " counter(page) " of " counter(pages);
            font-size: 9pt;
            font-family: Arial, sans-serif;
            color: #64748B;
          }
        }
        body {
          font-family: 'Segoe UI', Arial, sans-serif;
          color: #0F172A;
          line-height: 1.4;
          margin: 0;
          padding: 0;
        }
        .univ-header {
          text-align: center;
          border-bottom: 3px double #0F2C59;
          padding-bottom: 12px;
          margin-bottom: 16px;
        }
        .univ-name {
          font-size: 18pt;
          font-weight: 800;
          color: #0F2C59;
          text-transform: uppercase;
          letter-spacing: 0.5px;
          margin: 0;
        }
        .univ-subtitle {
          font-size: 9pt;
          color: #F26B21;
          font-weight: 700;
          text-transform: uppercase;
          letter-spacing: 1px;
          margin-top: 4px;
        }
        .univ-address {
          font-size: 8.5pt;
          color: #475569;
          margin-top: 2px;
        }
        .report-badge-bar {
          background-color: #F1F5F9;
          border-left: 4px solid #F26B21;
          padding: 10px 14px;
          margin-bottom: 16px;
          border-radius: 4px;
        }
        .report-title {
          font-size: 14pt;
          font-weight: 800;
          color: #0F2C59;
          margin: 0 0 6px 0;
        }
        .meta-grid {
          font-size: 9pt;
          color: #334155;
        }
        .meta-item {
          margin-bottom: 3px;
        }
        .data-table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 16px;
          margin-bottom: 24px;
        }
        .signature-block {
          margin-top: 40px;
          page-break-inside: avoid;
        }
        .sig-table {
          width: 100%;
          border: none;
        }
        .sig-cell {
          width: 33%;
          text-align: center;
          vertical-align: bottom;
          padding-top: 45px;
          font-size: 9.5pt;
          color: #0F2C59;
        }
        .sig-line {
          border-top: 1.5px solid #0F2C59;
          width: 80%;
          margin: 0 auto 6px auto;
        }
        .footer-note {
          font-size: 8pt;
          color: #94A3B8;
          text-align: center;
          margin-top: 24px;
          border-top: 1px solid #E2E8F0;
          padding-top: 8px;
        }
      </style>
    </head>
    <body>
      <div class="univ-header">
        <div class="univ-name">Swarrnim Startup &amp; Innovation University</div>
        <div class="univ-subtitle">NAAC Grade A+ Accredited • Government Recognized Statutory University</div>
        <div class="univ-address">Bhoyan Rathod, Opposite IFFCO Township, Gandhinagar-Ahmedabad Highway, Gujarat 382421</div>
      </div>

      <div class="report-badge-bar">
        <div class="report-title">${reportTitle}</div>
        <div class="meta-grid">
          <div class="meta-item"><strong>Generated On:</strong> ${timestamp}</div>
          <div class="meta-item"><strong>Generated By:</strong> ${userMeta?.name || 'Authorized ERP User'} (${userMeta?.designation || userMeta?.role || 'ERP Administrative Office'})</div>
          <div class="meta-item"><strong>Applied Scope / Filters:</strong> ${activeFilters}</div>
          <div class="meta-item"><strong>Total Records Exported:</strong> ${rows.length} Records</div>
        </div>
      </div>

      <table class="data-table">
        <thead>
          <tr>${tableHeaderHtml}</tr>
        </thead>
        <tbody>
          ${tableRowsHtml}
        </tbody>
      </table>

      <div class="signature-block">
        <table class="sig-table">
          <tr>
            <td class="sig-cell">
              <div class="sig-line"></div>
              <strong>Prepared By</strong><br/>
              <span style="font-size: 8.5pt; color: #64748B;">System Officer / ERP Custodian</span>
            </td>
            <td class="sig-cell">
              <div class="sig-line"></div>
              <strong>Verified By</strong><br/>
              <span style="font-size: 8.5pt; color: #64748B;">Head of Dept / Cell Director</span>
            </td>
            <td class="sig-cell">
              <div class="sig-line"></div>
              <strong>Sanctioned &amp; Sealed By</strong><br/>
              <span style="font-size: 8.5pt; color: #64748B;">Registrar / Controller of Exams</span>
            </td>
          </tr>
        </table>
      </div>

      <div class="footer-note">
        This is an official computer-generated document from Swarrnim ERP. Valid for statutory reporting (NAAC, UGC, AISHE, NIRF).
      </div>
    </body>
    </html>
  `;

  const blob = new Blob(['\ufeff' + htmlDocument], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  const sanitizedTitle = reportTitle.toLowerCase().replace(/[^a-z0-9]/g, '_');
  link.setAttribute('href', url);
  link.setAttribute('download', `ssiu_report_${sanitizedTitle}_${new Date().toISOString().split('T')[0]}.doc`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Official Centralized Excel Import Template Generator (.xlsx format data)
 */
export const downloadStudentImportTemplateExcel = () => {
  const headers = [
    'Enrollment No',
    'Student Name',
    'Institute',
    'Department',
    'Program',
    'Academic Year',
    'Semester',
    'Email',
    'Mobile'
  ];

  const sampleRows = [
    [
      '2026SITCE001',
      'Aarav Sharma',
      'Swarrnim Institute of Technology',
      'Computer Engineering',
      'B.Tech in Computer Engineering',
      '2024-2025',
      'Semester 1',
      'aarav.sharma@swarrnim.edu.in',
      '+91 98765 43210'
    ],
    [
      '2026AIN001',
      'Priya Patel',
      'Arihant Institute of Nursing',
      'N/A',
      'B.Sc. (Nursing)',
      '2024-2025',
      'Semester 1',
      'priya.patel@swarrnim.edu.in',
      '+91 98765 43211'
    ],
    [
      '2026SSMCLA001',
      'Rohan Mehta',
      'Swarrnim School of Management, Commerce & Liberal Arts',
      'N/A',
      'MBA',
      '2024-2025',
      'Semester 1',
      'rohan.mehta@swarrnim.edu.in',
      '+91 98765 43212'
    ]
  ];

  exportToExcel(
    'Student Import Official Master Template',
    headers,
    sampleRows,
    {},
    { name: 'SSIU Academic Administration', role: 'REGISTRAR' }
  );
};

export interface ExcelValidationError {
  rowNumber: number;
  field: string;
  value: string;
  reason: string;
}

/**
 * Validates uploaded Excel rows against Central Academic Master
 */
export const validateAcademicExcelRows = (
  rows: Record<string, string>[],
  institutes: { id: string; name: string; code: string }[],
  departments: { id: string; name: string; code: string; instituteId: string }[],
  programs: { id: string; name: string; code: string; instituteId: string; departmentId?: string }[]
): { isValid: boolean; errors: ExcelValidationError[] } => {
  const errors: ExcelValidationError[] = [];

  rows.forEach((row, idx) => {
    const rowNum = idx + 2; // Accounting for 1-based header row
    const instName = (row['Institute'] || row['institute'] || '').trim();
    const deptName = (row['Department'] || row['department'] || '').trim();
    const progName = (row['Program'] || row['program'] || '').trim();

    // 1. Validate Institute
    const matchedInst = institutes.find(i => 
      i.name.toLowerCase() === instName.toLowerCase() || 
      i.code.toLowerCase() === instName.toLowerCase() ||
      i.id.toLowerCase() === instName.toLowerCase()
    );

    if (!matchedInst) {
      errors.push({
        rowNumber: rowNum,
        field: 'Institute',
        value: instName,
        reason: `Invalid Institute: "${instName}". Value must match an active Institute in the Central Master.`
      });
      return;
    }

    // Check if institute requires departments
    const instDepts = departments.filter(d => d.instituteId === matchedInst.id);
    const hasDepartments = instDepts.length > 0;

    // 2. Validate Department
    let matchedDept: any = null;
    if (hasDepartments) {
      if (!deptName || deptName === 'N/A' || deptName === '-') {
        errors.push({
          rowNumber: rowNum,
          field: 'Department',
          value: deptName,
          reason: `Department is required for ${matchedInst.name}.`
        });
      } else {
        matchedDept = instDepts.find(d => 
          d.name.toLowerCase() === deptName.toLowerCase() || 
          d.code.toLowerCase() === deptName.toLowerCase()
        );
        if (!matchedDept) {
          errors.push({
            rowNumber: rowNum,
            field: 'Department',
            value: deptName,
            reason: `Invalid Department "${deptName}" for ${matchedInst.name}.`
          });
        }
      }
    }

    // 3. Validate Program
    const instPrograms = programs.filter(p => p.instituteId === matchedInst.id);
    const matchedProg = instPrograms.find(p => {
      const matchName = p.name.toLowerCase() === progName.toLowerCase() || p.code.toLowerCase() === progName.toLowerCase();
      if (!matchName) return false;
      if (hasDepartments && matchedDept) {
        return p.departmentId === matchedDept.id;
      }
      return true;
    });

    if (!matchedProg) {
      errors.push({
        rowNumber: rowNum,
        field: 'Program',
        value: progName,
        reason: `Invalid Program: "${progName}" for ${matchedInst.name}${matchedDept ? ` (${matchedDept.name})` : ''}.`
      });
    }
  });

  return {
    isValid: errors.length === 0,
    errors
  };
};

// ──────────────────────────────────────────────────────────────────────────────
// INVENTORY & ASSET EXCEL TEMPLATES & VALIDATORS
// ──────────────────────────────────────────────────────────────────────────────

export const downloadAssetImportTemplateExcel = () => {
  const headers = [
    'Asset Name',
    'Category Code (e.g. IT-COMP, IT-LAP, FURN-DESK, LAB-EQ)',
    'Institute Name / Code',
    'Department Name / Code',
    'Location (Room/Lab)',
    'Building & Floor',
    'Serial Number',
    'Model Number',
    'Manufacturer',
    'Purchase Date (YYYY-MM-DD)',
    'Purchase Cost (₹)',
    'Warranty End (YYYY-MM-DD)',
    'Vendor',
    'PO Number',
    'Condition (NEW/EXCELLENT/GOOD/FAIR)',
    'Processor (For PC)',
    'RAM (For PC)',
    'Storage (For PC)',
    'Operating System (For PC)',
    'Assigned Employee Code',
    'Assigned Employee Name'
  ];

  const sampleRows = [
    [
      'Dell OptiPlex 7000 Workstation',
      'IT-COMP',
      'Swarrnim Institute of Technology',
      'Computer Engineering',
      'A-204 AI Lab',
      'Engineering Block A, 2nd Floor',
      'DL-OPT-994182',
      'OptiPlex 7000',
      'Dell',
      '2026-08-01',
      78500,
      '2029-07-31',
      'Dell India Enterprises',
      'PO-SSIU-2026-01',
      'EXCELLENT',
      'Intel Core i7 12th Gen',
      '32 GB DDR4',
      '1 TB SSD + 2 TB HDD',
      'Windows 11 Pro',
      'EMP-SIT-042',
      'Dr. Aarav Mehta'
    ],
    [
      'Executive Mesh High-Back Chair',
      'FURN-CHAIR',
      'Swarrnim Institute of Technology',
      'Computer Engineering',
      'HOD Cabin A-201',
      'Engineering Block A, 2nd Floor',
      'CH-EX-0021',
      'ErgoMax Pro',
      'Godrej Interio',
      '2026-07-15',
      14500,
      '2028-07-14',
      'Godrej Commercial',
      'PO-SSIU-2026-04',
      'EXCELLENT',
      '',
      '',
      '',
      '',
      'EMP-SIT-001',
      'Dr. Manish Patel'
    ]
  ];

  const ws = XLSX.utils.aoa_to_sheet([headers, ...sampleRows]);
  ws['!cols'] = headers.map(() => ({ wch: 25 }));
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Asset_Import_Template');
  XLSX.writeFile(wb, 'Asset_Import_Template.xlsx');
};

export const downloadConsumableStockTemplateExcel = () => {
  const headers = [
    'Item Code (e.g. STN-A4, STN-TONER)',
    'Item Name',
    'Category Code (e.g. STN-PAPER, STN-OFF, STN-TONER)',
    'Unit (PCS/BOX/PACKET/REAM/SET/ROLL/KG/LITRE)',
    'Institute Name / Code',
    'Department Name / Code',
    'Storage Location',
    'Opening Quantity',
    'Minimum Stock Level',
    'Reorder Level',
    'Standard Rate (₹)'
  ];

  const sampleRows = [
    [
      'STN-A4-JK',
      'JK Copier A4 Paper 75 GSM (Ream of 500 Sheets)',
      'STN-PAPER',
      'REAM',
      'Swarrnim Institute of Technology',
      'Computer Engineering',
      'Department Store Cupboard A-201',
      100,
      25,
      50,
      340
    ],
    [
      'STN-TONER-HP88A',
      'HP 88A Black Original LaserJet Toner Cartridge',
      'STN-TONER',
      'PCS',
      'Swarrnim Institute of Technology',
      'Computer Engineering',
      'Department Store Cupboard A-201',
      15,
      8,
      15,
      3850
    ]
  ];

  const ws = XLSX.utils.aoa_to_sheet([headers, ...sampleRows]);
  ws['!cols'] = headers.map(() => ({ wch: 25 }));
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Consumables_Template');
  XLSX.writeFile(wb, 'Consumable_Stock_Template.xlsx');
};

export const downloadPhysicalFileTemplateExcel = () => {
  const headers = [
    'File Number / Reference',
    'File Title / Description',
    'File Category (EXAM_FILES/STUDENT_FILES/NAAC_IQAC_FILES/ADMISSION_FILES/FINANCE_FILES/DEPT_FILES)',
    'Institute Name / Code',
    'Department Name / Code',
    'Academic Year (e.g. 2025-2026)',
    'Document Year (YYYY)',
    'Storage Location Room',
    'Rack Number (e.g. R-04)',
    'Shelf Number (e.g. S-02)',
    'Box Number (e.g. B-18)',
    'Custodian Name',
    'Custodian Employee ID',
    'Date Opened (YYYY-MM-DD)',
    'Retention Until (YYYY-MM-DD)',
    'Status (ACTIVE/ARCHIVED)'
  ];

  const sampleRows = [
    [
      'EXAM/REG/2026/001',
      'Summer 2026 Regular Examination Sanction & Result Gazette',
      'EXAM_FILES',
      'Swarrnim Institute of Technology',
      'Computer Engineering',
      '2025-2026',
      2026,
      'Statutory Document Archive ARC-101',
      'Rack R-04',
      'Shelf S-02',
      'Box B-18',
      'Dr. Sanjay Patel',
      'EMP-SSIU-004',
      '2026-05-10',
      '2036-05-09',
      'ACTIVE'
    ]
  ];

  const ws = XLSX.utils.aoa_to_sheet([headers, ...sampleRows]);
  ws['!cols'] = headers.map(() => ({ wch: 25 }));
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Physical_Files_Template');
  XLSX.writeFile(wb, 'Physical_File_Register_Template.xlsx');
};

export const downloadAssetAssignmentTemplateExcel = () => {
  const headers = [
    'Asset ID / Tag (e.g. SIT-CE-PC-0001)',
    'Assigned To Employee Code',
    'Assigned To Name',
    'Designation',
    'Location / Room No',
    'Issue Date (YYYY-MM-DD)',
    'Expected Return Date (YYYY-MM-DD)',
    'Condition at Issue (NEW/EXCELLENT/GOOD/FAIR)',
    'Purpose / Remarks'
  ];

  const sampleRows = [
    [
      'SIT-CE-PC-0001',
      'EMP-SIT-042',
      'Dr. Aarav Mehta',
      'Professor & Lab Incharge',
      'Engineering Block A (A-204)',
      '2026-08-01',
      '2027-07-31',
      'EXCELLENT',
      'Allocated for AI Research & Lab Instruction'
    ]
  ];

  const ws = XLSX.utils.aoa_to_sheet([headers, ...sampleRows]);
  ws['!cols'] = headers.map(() => ({ wch: 25 }));
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Asset_Assignment_Template');
  XLSX.writeFile(wb, 'Employee_Asset_Assignment_Template.xlsx');
};

export const validateAssetExcelRows = (
  rows: any[],
  institutes: any[],
  departments: any[],
  categories: any[]
): { isValid: boolean; errors: { rowNumber: number; field: string; value: any; reason: string }[]; validatedData: any[] } => {
  const errors: { rowNumber: number; field: string; value: any; reason: string }[] = [];
  const validatedData: any[] = [];

  rows.forEach((row, idx) => {
    const rowNum = idx + 2;
    const name = row['Asset Name'] || row['name'];
    const catCode = row['Category Code (e.g. IT-COMP, IT-LAP, FURN-DESK, LAB-EQ)'] || row['categoryId'] || row['categoryCode'];
    const instName = row['Institute Name / Code'] || row['instituteName'] || row['instituteId'];
    const deptName = row['Department Name / Code'] || row['departmentName'] || row['departmentId'];

    if (!name) {
      errors.push({ rowNumber: rowNum, field: 'Asset Name', value: name, reason: 'Asset Name is required.' });
    }

    // Validate Institute
    const matchedInst = institutes.find(i =>
      i.name.toLowerCase() === (instName || '').toLowerCase() ||
      i.code.toLowerCase() === (instName || '').toLowerCase() ||
      i.id === instName
    );

    if (!matchedInst) {
      errors.push({ rowNumber: rowNum, field: 'Institute', value: instName, reason: `Unknown Institute "${instName}".` });
      return;
    }

    // Validate Department if institute has departments
    const instDepts = departments.filter(d => d.instituteId === matchedInst.id);
    let matchedDept: any = undefined;
    if (instDepts.length > 0) {
      matchedDept = instDepts.find(d =>
        d.name.toLowerCase() === (deptName || '').toLowerCase() ||
        d.code.toLowerCase() === (deptName || '').toLowerCase() ||
        d.id === deptName
      );
      if (!matchedDept && deptName && deptName !== 'N/A') {
        errors.push({ rowNumber: rowNum, field: 'Department', value: deptName, reason: `Invalid Department "${deptName}" for ${matchedInst.name}.` });
      }
    }

    // Validate Category
    const matchedCat = categories.find(c =>
      c.code.toLowerCase() === (catCode || '').toLowerCase() ||
      c.id === catCode ||
      c.name.toLowerCase() === (catCode || '').toLowerCase()
    );

    if (!matchedCat) {
      errors.push({ rowNumber: rowNum, field: 'Category', value: catCode, reason: `Unknown Category Code "${catCode}".` });
    }

    if (errors.filter(e => e.rowNumber === rowNum).length === 0) {
      validatedData.push({
        name,
        categoryId: matchedCat?.id || 'cat-it-1',
        categoryName: matchedCat?.name || 'IT Equipment',
        categoryGroup: matchedCat?.categoryGroup || 'IT_EQUIPMENT',
        instituteId: matchedInst.id,
        instituteName: matchedInst.name,
        departmentId: matchedDept?.id,
        departmentName: matchedDept?.name,
        locationName: row['Location (Room/Lab)'] || 'Department Store',
        building: row['Building & Floor'] || 'Engineering Block A',
        serialNumber: row['Serial Number'],
        modelNumber: row['Model Number'],
        manufacturer: row['Manufacturer'],
        purchaseDate: row['Purchase Date (YYYY-MM-DD)'] || new Date().toISOString().split('T')[0],
        purchaseCost: Number(row['Purchase Cost (₹)'] || 0),
        currentValue: Number(row['Purchase Cost (₹)'] || 0),
        warrantyEnd: row['Warranty End (YYYY-MM-DD)'],
        vendor: row['Vendor'],
        purchaseOrderNumber: row['PO Number'],
        assetCondition: row['Condition (NEW/EXCELLENT/GOOD/FAIR)'] || 'GOOD',
        status: row['Assigned Employee Name'] ? 'ASSIGNED' : 'IN_STORE',
        assignedToName: row['Assigned Employee Name'],
        assignedToEmpCode: row['Assigned Employee Code'],
        cpuConfig: (matchedCat?.categoryGroup === 'IT_EQUIPMENT' && row['Processor (For PC)']) ? {
          processor: row['Processor (For PC)'],
          ram: row['RAM (For PC)'] || '16 GB',
          storageCapacity: row['Storage (For PC)'] || '512 GB SSD',
          os: row['Operating System (For PC)'] || 'Windows 11'
        } : undefined
      });
    }
  });

  return { isValid: errors.length === 0, errors, validatedData };
};

export const validateConsumableExcelRows = (
  rows: any[],
  institutes: any[],
  departments: any[],
  categories: any[]
): { isValid: boolean; errors: { rowNumber: number; field: string; value: any; reason: string }[]; validatedData: any[] } => {
  const errors: { rowNumber: number; field: string; value: any; reason: string }[] = [];
  const validatedData: any[] = [];

  rows.forEach((row, idx) => {
    const rowNum = idx + 2;
    const itemCode = row['Item Code (e.g. STN-A4, STN-TONER)'] || row['itemCode'];
    const name = row['Item Name'] || row['name'];
    const catCode = row['Category Code (e.g. STN-PAPER, STN-OFF, STN-TONER)'] || row['categoryId'];
    const unit = row['Unit (PCS/BOX/PACKET/REAM/SET/ROLL/KG/LITRE)'] || row['unit'] || 'PCS';
    const instName = row['Institute Name / Code'] || row['instituteName'];
    const deptName = row['Department Name / Code'] || row['departmentName'];

    if (!name) errors.push({ rowNumber: rowNum, field: 'Item Name', value: name, reason: 'Item Name is required.' });

    const matchedInst = institutes.find(i =>
      i.name.toLowerCase() === (instName || '').toLowerCase() ||
      i.code.toLowerCase() === (instName || '').toLowerCase()
    );

    if (!matchedInst) {
      errors.push({ rowNumber: rowNum, field: 'Institute', value: instName, reason: `Unknown Institute "${instName}".` });
      return;
    }

    const instDepts = departments.filter(d => d.instituteId === matchedInst.id);
    let matchedDept: any = undefined;
    if (instDepts.length > 0 && deptName && deptName !== 'N/A') {
      matchedDept = instDepts.find(d =>
        d.name.toLowerCase() === deptName.toLowerCase() ||
        d.code.toLowerCase() === deptName.toLowerCase()
      );
    }

    const matchedCat = categories.find(c =>
      c.code.toLowerCase() === (catCode || '').toLowerCase() ||
      c.id === catCode ||
      c.name.toLowerCase() === (catCode || '').toLowerCase()
    );

    if (errors.filter(e => e.rowNumber === rowNum).length === 0) {
      validatedData.push({
        itemCode: itemCode || `STN-${Date.now().toString().slice(-4)}`,
        name,
        categoryId: matchedCat?.id || 'cat-stn-1',
        categoryName: matchedCat?.name || 'Stationery',
        categoryGroup: matchedCat?.categoryGroup || 'STATIONERY_CONSUMABLES',
        unit,
        instituteId: matchedInst.id,
        instituteName: matchedInst.name,
        departmentId: matchedDept?.id,
        departmentName: matchedDept?.name,
        locationName: row['Storage Location'] || 'Department Store',
        openingQuantity: Number(row['Opening Quantity'] || 0),
        minimumStockLevel: Number(row['Minimum Stock Level'] || 10),
        reorderLevel: Number(row['Reorder Level'] || 25),
        standardRate: Number(row['Standard Rate (₹)'] || 0)
      });
    }
  });

  return { isValid: errors.length === 0, errors, validatedData };
};


