/**
 * Canonical ERP System Permissions
 * Centralized definition of all operational and data access permissions across the SSIU ERP.
 */

export type ERPPermission =
  // Student Management
  | 'VIEW_STUDENT'
  | 'CREATE_STUDENT'
  | 'EDIT_STUDENT'
  | 'DELETE_STUDENT'
  | 'EXPORT_STUDENT'
  | 'VERIFY_STUDENT_DOCUMENT'
  | 'VIEW_STUDENT_PROFILE'
  | 'EDIT_STUDENT_PROFILE'

  // Faculty & Staff Management
  | 'VIEW_FACULTY'
  | 'CREATE_FACULTY'
  | 'EDIT_FACULTY'
  | 'DELETE_FACULTY'
  | 'EXPORT_FACULTY'
  | 'ASSIGN_FACULTY_WORKLOAD'
  | 'VIEW_FACULTY_WORKLOAD'

  // Organization & Department Hierarchy
  | 'VIEW_ORGANIZATION'
  | 'MANAGE_ORGANIZATION'
  | 'VIEW_INSTITUTE'
  | 'MANAGE_INSTITUTE'
  | 'VIEW_DEPARTMENT'
  | 'MANAGE_DEPARTMENT'
  | 'APPOINT_HOD'
  | 'VIEW_PROGRAM'
  | 'MANAGE_PROGRAM'

  // Academic & Attendance
  | 'VIEW_ATTENDANCE'
  | 'TAKE_ATTENDANCE'
  | 'EDIT_ATTENDANCE'
  | 'EXPORT_ATTENDANCE'
  | 'VIEW_SESSION_PLAN'
  | 'MANAGE_SESSION_PLAN'
  | 'VIEW_STUDY_MATERIAL'
  | 'UPLOAD_STUDY_MATERIAL'
  | 'VIEW_ACADEMIC_CALENDAR'
  | 'MANAGE_ACADEMIC_CALENDAR'

  // Examination & Eligibility
  | 'VIEW_EXAMINATION'
  | 'MANAGE_EXAMINATION'
  | 'VIEW_EXAM_ELIGIBILITY'
  | 'ENDORSE_EXAM_ELIGIBILITY'
  | 'APPROVE_EXAM_ELIGIBILITY'
  | 'GENERATE_HALL_TICKET'
  | 'ENTER_MARKS'
  | 'PUBLISH_RESULTS'

  // Workflows, Requests & Approvals
  | 'CREATE_REQUEST'
  | 'VIEW_REQUEST'
  | 'APPROVE_REQUEST'
  | 'REJECT_REQUEST'
  | 'ESCALATE_REQUEST'
  | 'MANAGE_APPROVAL_WORKFLOW'

  // Inventory & Fixed Assets
  | 'VIEW_ASSET'
  | 'CREATE_ASSET'
  | 'EDIT_ASSET'
  | 'DELETE_ASSET'
  | 'ASSIGN_ASSET'
  | 'TRANSFER_ASSET'
  | 'RETURN_ASSET'
  | 'REPLACE_ASSET'
  | 'REPORT_ASSET_ISSUE'
  | 'MANAGE_ASSET_MAINTENANCE'
  | 'PERFORM_ASSET_VERIFICATION'
  | 'DISPOSE_ASSET'
  | 'EXPORT_ASSET'

  // Finance & Accounts
  | 'VIEW_FEE'
  | 'COLLECT_FEE'
  | 'GENERATE_INVOICE'
  | 'APPROVE_CONCESSION'
  | 'PROCESS_REFUND'
  | 'VIEW_FINANCIAL_REPORTS'

  // Notesheet & Governance
  | 'CREATE_NOTESHEET'
  | 'VIEW_NOTESHEET'
  | 'FORWARD_NOTESHEET'
  | 'APPROVE_NOTESHEET'
  | 'REJECT_NOTESHEET'
  | 'AUDIT_NOTESHEET'

  // Feedback & IQAC
  | 'SUBMIT_FEEDBACK'
  | 'VIEW_FEEDBACK'
  | 'RESOLVE_FEEDBACK'
  | 'VIEW_IQAC_ANALYTICS'

  // Reports & Analytics
  | 'VIEW_REPORTS'
  | 'EXPORT_DATA'
  | 'GENERATE_NAAC_REPORT'
  | 'GENERATE_NBA_REPORT'

  // System Administration & Security
  | 'VIEW_AUDIT_LOG'
  | 'MANAGE_USERS'
  | 'MANAGE_ROLES'
  | 'MANAGE_SECURITY_SETTINGS'
  | 'RESET_SYSTEM_DATABASE';

export const ALL_PERMISSIONS: ERPPermission[] = [
  'VIEW_STUDENT', 'CREATE_STUDENT', 'EDIT_STUDENT', 'DELETE_STUDENT', 'EXPORT_STUDENT', 'VERIFY_STUDENT_DOCUMENT', 'VIEW_STUDENT_PROFILE', 'EDIT_STUDENT_PROFILE',
  'VIEW_FACULTY', 'CREATE_FACULTY', 'EDIT_FACULTY', 'DELETE_FACULTY', 'EXPORT_FACULTY', 'ASSIGN_FACULTY_WORKLOAD', 'VIEW_FACULTY_WORKLOAD',
  'VIEW_ORGANIZATION', 'MANAGE_ORGANIZATION', 'VIEW_INSTITUTE', 'MANAGE_INSTITUTE', 'VIEW_DEPARTMENT', 'MANAGE_DEPARTMENT', 'APPOINT_HOD', 'VIEW_PROGRAM', 'MANAGE_PROGRAM',
  'VIEW_ATTENDANCE', 'TAKE_ATTENDANCE', 'EDIT_ATTENDANCE', 'EXPORT_ATTENDANCE', 'VIEW_SESSION_PLAN', 'MANAGE_SESSION_PLAN', 'VIEW_STUDY_MATERIAL', 'UPLOAD_STUDY_MATERIAL', 'VIEW_ACADEMIC_CALENDAR', 'MANAGE_ACADEMIC_CALENDAR',
  'VIEW_EXAMINATION', 'MANAGE_EXAMINATION', 'VIEW_EXAM_ELIGIBILITY', 'ENDORSE_EXAM_ELIGIBILITY', 'APPROVE_EXAM_ELIGIBILITY', 'GENERATE_HALL_TICKET', 'ENTER_MARKS', 'PUBLISH_RESULTS',
  'CREATE_REQUEST', 'VIEW_REQUEST', 'APPROVE_REQUEST', 'REJECT_REQUEST', 'ESCALATE_REQUEST', 'MANAGE_APPROVAL_WORKFLOW',
  'VIEW_ASSET', 'CREATE_ASSET', 'EDIT_ASSET', 'DELETE_ASSET', 'ASSIGN_ASSET', 'TRANSFER_ASSET', 'RETURN_ASSET', 'REPLACE_ASSET', 'REPORT_ASSET_ISSUE', 'MANAGE_ASSET_MAINTENANCE', 'PERFORM_ASSET_VERIFICATION', 'DISPOSE_ASSET', 'EXPORT_ASSET',
  'VIEW_FEE', 'COLLECT_FEE', 'GENERATE_INVOICE', 'APPROVE_CONCESSION', 'PROCESS_REFUND', 'VIEW_FINANCIAL_REPORTS',
  'CREATE_NOTESHEET', 'VIEW_NOTESHEET', 'FORWARD_NOTESHEET', 'APPROVE_NOTESHEET', 'REJECT_NOTESHEET', 'AUDIT_NOTESHEET',
  'SUBMIT_FEEDBACK', 'VIEW_FEEDBACK', 'RESOLVE_FEEDBACK', 'VIEW_IQAC_ANALYTICS',
  'VIEW_REPORTS', 'EXPORT_DATA', 'GENERATE_NAAC_REPORT', 'GENERATE_NBA_REPORT',
  'VIEW_AUDIT_LOG', 'MANAGE_USERS', 'MANAGE_ROLES', 'MANAGE_SECURITY_SETTINGS', 'RESET_SYSTEM_DATABASE'
];
